CREATE TABLE  /*TABLE_PREFIX*/t_trezor (
  s_address VARCHAR( 34 ) NOT NULL ,
  fk_i_user_id INT NOT NULL ,
  b_admin TINYINT(1) NOT NULL DEFAULT 0,

  PRIMARY KEY (s_address, b_admin)
) ENGINE=MyISAM DEFAULT CHARACTER SET 'UTF8' COLLATE 'UTF8_GENERAL_CI';


